server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: demothree
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      springframework: DEBUG