server:
  port: 8082

spring:
  application:
    name: demosix
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        format_sql: true
    show-sql: true

logging:
  level:
    io:
      github:
        resilience4j:
          retry: DEBUG
          circuitbreaker: DEBUG
    org:
      springframework:
        transaction: DEBUG
        retry: DEBUG
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        sliding-window-size: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 1
  retry:
    instances:
      customerService:
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true


