apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-prod-config-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-prod-config-secret
  template:
    metadata:
      labels:
        app: myapp-prod-config-secret
    spec:
      containers:
        - name: myapp
          image: keziaeka/demo-three:prod-1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.properties
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-prod
                  key: spring.datasource.password
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: app-config-prod