apiVersion: v1
kind: Service
metadata:
  name: myapp-prod-config-secret
spec:
  type: NodePort
  selector:
    app: myapp-prod-config-secret
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082