version: '3.8'

services:
  bca-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: keziaeka/demo-three:prod-1.0.0
    container_name: bca-app-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod