version: '3.8'

services:
  bca-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: keziaeka/demo-three:dev-1.0.0
    container_name: bca-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev